language: node_js

sudo: false

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - GITHUB_REPO: github.com/TopUnicorn2020/sites
    - CODING_REPO: github.com/TopUnicorn2020/sites

before_install:
  - export TZ=Asia/Shanghai

script:
  - yarn run build

after_success:
  - git config user.name "TopUnicorn2020"
  - git config user.email "jiarong.zhao@topevery.club"
  - git clone https://${CODING_REPO} ./old-docs
  - cp -r ./old-docs/.git ./docs 
  - cd ./docs
  - git add -A
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git branch -a
  - git push --force --quiet "https://TopUnicorn2020:${CI_TOKEN}@${GITHUB_REPO}" gh-pages:gh-pages
